version: "1.0"
info:
  model: int-scaffold
packages:
- name: SerGHAWSUS1011Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
- name: AzRepoMultiplyPackage
  version: "1.0"
  gitServerName: srcCtrl_AzRepos_Arti
  gitUrl: https://dev.azure.com/ArtiKhare/AzRepoMultiplyPackage/_git
  gitUsername: ArtiKhare
  gitBranch: main
services:
- serviceName: project.serghawsus1011.integrations:azrepoPackage
  packages:
  - name: SerGHAWSUS1011Project
    version: "1.0"
  - name: AzRepoMultiplyPackage
    version: "1.0"
- serviceName: AzRepoMultiplyPackage:multiplyFS
  packages:
  - name: AzRepoMultiplyPackage
    version: "1.0"
- serviceName: pub.math:multiplyInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
